runtime: nodejs
vm: true

resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10

manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: IGNORED
  secure: always

env_variables:
  EWORKER_ENV: 'production'

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
